environment: "development"
aligned_layer_deployment_config_file_path: "./contracts/script/output/devnet/alignedlayer_deployment_output.json"
eigen_layer_deployment_config_file_path: "./contracts/script/output/devnet/eigenlayer_deployment_output.json"
eth_rpc_url: "http://localhost:8545"
eth_ws_url: "ws://localhost:8545"
ecdsa_private_key_store_path: "./operator/config/devnet/keys/operator.ecdsa.key.json"
ecdsa_private_key_store_password: ""
bls_private_key_store_path: "./operator/config/devnet/keys/operator.bls.key.json"
bls_private_key_store_password: ""
eigen_metrics_ip_port_address: "localhost:9090"