[package]
name = "fibonacci-guest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "guest"
path = "./src/lib.rs"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", git = "https://github.com/PatStiles/Lasso.git", branch = "feat/integration_changes" }