global:
  scrape_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: "aligned-aggregator"
    scrape_interval: 1s
    static_configs:
      - targets: ["host.docker.internal:9091"]
        labels:
          bot: "aggregator"

  - job_name: "aligned-operator"
    scrape_interval: 1s
    static_configs:
      - targets: [ "host.docker.internal:9092" ]
        labels:
          bot: "operator"
  
  - job_name: "aligned-batcher"
    scrape_interval: 1s
    static_configs:
      - targets: [ "host.docker.internal:9093" ]
        labels:
          bot: "batcher"
  
  - job_name: "aligned-tracker"
    scrape_interval: 1s
    static_configs:
      - targets: [ "host.docker.internal:4001" ]
        labels:
          bot: "tracker"
