# Common variables for all the services
# 'production' only prints info and above. 'development' also prints debug
environment: "production"
aligned_layer_deployment_config_file_path: "./contracts/script/output/holesky/alignedlayer_deployment_output.json"
eigen_layer_deployment_config_file_path: "./contracts/script/output/holesky/eigenlayer_deployment_output.json"
eth_rpc_url: "https://ethereum-holesky-rpc.publicnode.com"
eth_ws_url: "wss://ethereum-holesky-rpc.publicnode.com"
eigen_metrics_ip_port_address: "localhost:9090"

## ECDSA Configurations
ecdsa:
  private_key_store_path: "<ecdsa_key_store_location_path>"
  private_key_store_password: "<ecdsa_key_store_password>"

## BLS Configurations
bls:
  private_key_store_path: "<bls_key_store_location_path>"
  private_key_store_password: "<bls_key_store_password>"

## Operator Configurations
operator:
  aggregator_rpc_server_ip_port_address: aggregator.alignedlayer.com:8090
  address: "<operator_address>"
  earnings_receiver_address: "<earnings_receiver_address>" #Can be the same as the operator.
  delegation_approver_address: "0x0000000000000000000000000000000000000000"
  staker_opt_out_window_blocks: 0
  metadata_url: "https://yetanotherco.github.io/operator_metadata/metadata.json"
  enable_metrics: true
  metrics_ip_port_address: localhost:9092
  max_batch_size: 268435456 # 256 MiB
