[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", tag = "v1.0.1" }

[package.metadata.risc0]
methods = ["guest"]
